#!/usr/bin/env python3
"""
Visualize SimAI topology files (generated by gen_Topo_Template*.py).

This script parses both topology header formats:
1) old: node_num gpus_per_server nvswitch_num switch_num link_num gpu_type
2) new: node_num gpus_per_server nvswitch_num switch_num optical_module_num link_num gpu_type
"""

from __future__ import annotations

import argparse
import math
import os
import shutil
import subprocess
import tempfile
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Set, Tuple

Role = str
Edge = Tuple[int, int]


@dataclass
class Topology:
    node_num: int
    gpu_per_server: int
    nvswitch_num: int
    switch_num: int
    optical_module_num: int
    link_num_declared: int
    gpu_type: str
    switch_nodes: List[int]
    edge_counts: Dict[Edge, int]


def parse_header(parts: List[str]) -> Tuple[int, int, int, int, int, int, str]:
    if len(parts) == 7:
        node_num, gpu_per_server, nvswitch_num, switch_num, optical_module_num, link_num = map(
            int, parts[:6]
        )
        gpu_type = parts[6]
    elif len(parts) == 6:
        node_num, gpu_per_server, nvswitch_num, switch_num, link_num = map(int, parts[:5])
        optical_module_num = 0
        gpu_type = parts[5]
    else:
        raise ValueError(
            "Unsupported header format. Expect 6 or 7 columns, got: "
            + " ".join(parts)
        )
    return (
        node_num,
        gpu_per_server,
        nvswitch_num,
        switch_num,
        optical_module_num,
        link_num,
        gpu_type,
    )


def parse_topology(path: Path) -> Topology:
    with path.open("r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]

    if len(lines) < 2:
        raise ValueError(f"Invalid topology file: {path} (less than 2 non-empty lines)")

    (
        node_num,
        gpu_per_server,
        nvswitch_num,
        switch_num,
        optical_module_num,
        link_num_declared,
        gpu_type,
    ) = parse_header(lines[0].split())

    switch_nodes = [int(x) for x in lines[1].split()]

    edge_counts: Dict[Edge, int] = defaultdict(int)
    for line in lines[2:]:
        parts = line.split()
        if len(parts) < 2:
            continue
        src = int(parts[0])
        dst = int(parts[1])
        if src == dst:
            continue
        edge = (src, dst) if src < dst else (dst, src)
        edge_counts[edge] += 1

    return Topology(
        node_num=node_num,
        gpu_per_server=gpu_per_server,
        nvswitch_num=nvswitch_num,
        switch_num=switch_num,
        optical_module_num=optical_module_num,
        link_num_declared=link_num_declared,
        gpu_type=gpu_type,
        switch_nodes=switch_nodes,
        edge_counts=dict(edge_counts),
    )


def build_adjacency(edges: Iterable[Edge]) -> Dict[int, Set[int]]:
    adjacency: Dict[int, Set[int]] = defaultdict(set)
    for u, v in edges:
        adjacency[u].add(v)
        adjacency[v].add(u)
    return adjacency


def classify_nodes(topo: Topology) -> Tuple[Dict[int, Role], Dict[Role, Set[int]]]:
    gpu_num = topo.node_num - (topo.nvswitch_num + topo.switch_num + topo.optical_module_num)
    if gpu_num < 0:
        raise ValueError(
            "Invalid header counts: computed GPU count < 0. "
            f"node_num={topo.node_num}, nvswitch_num={topo.nvswitch_num}, "
            f"switch_num={topo.switch_num}, optical_module_num={topo.optical_module_num}"
        )

    all_nodes = set(range(topo.node_num))
    gpu_nodes = set(range(gpu_num))

    expected_switch_count = topo.nvswitch_num + topo.switch_num + topo.optical_module_num
    switch_nodes = topo.switch_nodes
    if len(switch_nodes) != expected_switch_count:
        switch_nodes = list(range(gpu_num, topo.node_num))

    nvswitch_nodes = set(switch_nodes[: topo.nvswitch_num])
    if topo.optical_module_num > 0:
        optical_nodes = set(switch_nodes[-topo.optical_module_num :])
        middle_switch_nodes = set(
            switch_nodes[topo.nvswitch_num : -topo.optical_module_num]
        )
    else:
        optical_nodes = set()
        middle_switch_nodes = set(switch_nodes[topo.nvswitch_num :])

    adjacency = build_adjacency(topo.edge_counts.keys())
    asw_nodes = {
        node for node in middle_switch_nodes if adjacency.get(node, set()) & gpu_nodes
    }
    psw_nodes = middle_switch_nodes - asw_nodes

    role_map: Dict[int, Role] = {}
    for node in all_nodes:
        if node in gpu_nodes:
            role_map[node] = "GPU"
        elif node in nvswitch_nodes:
            role_map[node] = "NVSwitch"
        elif node in asw_nodes:
            role_map[node] = "ASW"
        elif node in psw_nodes:
            role_map[node] = "PSW"
        elif node in optical_nodes:
            role_map[node] = "Optical"
        else:
            role_map[node] = "Unknown"

    grouped: Dict[Role, Set[int]] = {
        "GPU": gpu_nodes,
        "NVSwitch": nvswitch_nodes,
        "ASW": asw_nodes,
        "Optical": optical_nodes,
        "PSW": psw_nodes,
        "Unknown": {node for node, role in role_map.items() if role == "Unknown"},
    }
    return role_map, grouped


def edge_kind(role_u: Role, role_v: Role) -> str:
    pair = tuple(sorted((role_u, role_v)))
    if pair == ("GPU", "NVSwitch"):
        return "GPU-NV"
    if pair == ("ASW", "GPU"):
        return "GPU-ASW"
    if pair == ("ASW", "PSW"):
        return "ASW-PSW"
    if pair == ("ASW", "Optical"):
        return "ASW-Optical"
    if pair == ("Optical", "PSW"):
        return "Optical-PSW"
    return "Other"


def build_dot(
    topo: Topology,
    show_labels: bool,
    max_auto_labels: int,
    rankdir: str,
) -> str:
    role_map, grouped = classify_nodes(topo)
    enable_labels = show_labels or topo.node_num <= max_auto_labels

    node_colors = {
        "GPU": "#4E79A7",
        "NVSwitch": "#F28E2B",
        "ASW": "#59A14F",
        "PSW": "#E15759",
        "Optical": "#76B7B2",
        "Unknown": "#9D7660",
    }
    edge_colors = {
        "GPU-NV": "#F28E2B",
        "GPU-ASW": "#4E79A7",
        "ASW-PSW": "#7F7F7F",
        "ASW-Optical": "#76B7B2",
        "Optical-PSW": "#76B7B2",
        "Other": "#B0B0B0",
    }

    role_order = ["GPU", "NVSwitch", "ASW", "Optical", "PSW", "Unknown"]
    lines: List[str] = []
    lines.append("graph topo {")
    lines.append(
        f'  graph [layout=dot, rankdir={rankdir}, overlap=false, splines=true, nodesep=0.2, ranksep=0.8];'
    )
    lines.append('  node [shape=circle, style=filled, fontsize=9, width=0.26, height=0.26, penwidth=0.5, color="#333333"];')
    lines.append('  edge [color="#777777", arrowsize=0.4];')
    lines.append(
        '  label="Topology Visualization '
        f'({topo.gpu_type}) | nodes={topo.node_num}, links(unique)={len(topo.edge_counts)}, '
        f'links(declared)={topo.link_num_declared}";'
    )
    lines.append('  labelloc="t";')
    lines.append('  fontsize=14;')

    for role in role_order:
        nodes = sorted(grouped[role])
        if not nodes:
            continue
        lines.append(f"  subgraph cluster_{role} {{")
        lines.append(f'    label="{role} ({len(nodes)})";')
        lines.append('    color="#D0D0D0";')
        lines.append('    style="rounded,dashed";')
        lines.append("    rank=same;")
        for node in nodes:
            label = str(node) if enable_labels else ""
            lines.append(
                f'    {node} [fillcolor="{node_colors[role]}", label="{label}", tooltip="{role}:{node}"];'
            )
        lines.append("  }")

    ordered_non_empty_roles = [role for role in role_order if grouped[role]]
    anchor_of_role: Dict[str, int] = {}
    for role in ordered_non_empty_roles:
        anchor_of_role[role] = min(grouped[role])
    for i in range(len(ordered_non_empty_roles) - 1):
        left_role = ordered_non_empty_roles[i]
        right_role = ordered_non_empty_roles[i + 1]
        left_node = anchor_of_role[left_role]
        right_node = anchor_of_role[right_role]
        lines.append(
            f'  {left_node} -- {right_node} [style=invis, weight=200, constraint=true];'
        )

    for (u, v), count in topo.edge_counts.items():
        kind = edge_kind(role_map.get(u, "Unknown"), role_map.get(v, "Unknown"))
        color = edge_colors[kind]
        penwidth = 0.5 + min(math.log2(count + 1), 5.0) * 0.35
        attrs = [f'color="{color}"', f'penwidth="{penwidth:.2f}"']
        if count > 1 and topo.node_num <= 256:
            attrs.append(f'label="{count}"')
            attrs.append('fontsize="7"')
        lines.append(f"  {u} -- {v} [{', '.join(attrs)}];")

    lines.append("}")
    return "\n".join(lines) + "\n"


def render_with_dot(dot_text: str, output_path: Path, keep_dot: bool) -> Path:
    if shutil.which("dot") is None:
        raise RuntimeError("Graphviz 'dot' command not found. Please install graphviz first.")

    output_ext = output_path.suffix.lower().lstrip(".")
    if output_ext not in {"png", "svg", "pdf", "dot"}:
        raise ValueError("Unsupported output format. Use one of: .png .svg .pdf .dot")

    if output_ext == "dot":
        output_path.write_text(dot_text, encoding="utf-8")
        return output_path

    temp_dot = tempfile.NamedTemporaryFile(mode="w", suffix=".dot", delete=False, encoding="utf-8")
    temp_dot_path = Path(temp_dot.name)
    try:
        temp_dot.write(dot_text)
        temp_dot.close()
        cmd = ["dot", f"-T{output_ext}", str(temp_dot_path), "-o", str(output_path)]
        subprocess.run(cmd, check=True)
    finally:
        if keep_dot:
            dot_path = output_path.with_suffix(".dot")
            dot_path.write_text(dot_text, encoding="utf-8")
        if temp_dot_path.exists():
            os.remove(temp_dot_path)

    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize SimAI topology txt as graph image.")
    parser.add_argument(
        "input_topo",
        type=Path,
        help="Path to topology text file generated by gen_Topo_Template*.py",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Output path (.png/.svg/.pdf/.dot). Default: <input>.svg",
    )
    parser.add_argument(
        "--show-labels",
        action="store_true",
        help="Force node-id labels on. Default is auto by node count.",
    )
    parser.add_argument(
        "--max-auto-labels",
        type=int,
        default=96,
        help="Auto show labels when node count <= this value.",
    )
    parser.add_argument(
        "--rankdir",
        type=str,
        choices=["LR", "TB", "RL", "BT"],
        default="LR",
        help="Graph direction. Use TB to rotate 90 degrees from default LR.",
    )
    parser.add_argument(
        "--horizontal",
        action="store_true",
        help="Convenience flag: rotate graph to horizontal rows (same as --rankdir TB).",
    )
    parser.add_argument(
        "--keep-dot",
        action="store_true",
        help="Keep generated dot source as <output>.dot when rendering image.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = args.input_topo
    if not input_path.exists():
        raise FileNotFoundError(f"Input topo file not found: {input_path}")

    output_path = args.output if args.output else input_path.with_suffix(".svg")
    topo = parse_topology(input_path)
    rankdir = "TB" if args.horizontal else args.rankdir

    dot_text = build_dot(
        topo=topo,
        show_labels=bool(args.show_labels),
        max_auto_labels=args.max_auto_labels,
        rankdir=rankdir,
    )
    out = render_with_dot(dot_text, output_path=output_path, keep_dot=bool(args.keep_dot))
    _, grouped = classify_nodes(topo)

    print(f"Input : {input_path}")
    print(f"Output: {out}")
    print(
        "Node Roles: "
        f"GPU={len(grouped['GPU'])}, NVSwitch={len(grouped['NVSwitch'])}, "
        f"ASW={len(grouped['ASW'])}, PSW={len(grouped['PSW'])}, "
        f"Optical={len(grouped['Optical'])}, Unknown={len(grouped['Unknown'])}"
    )
    print(
        "Links    : "
        f"declared={topo.link_num_declared}, aggregated_unique={len(topo.edge_counts)}"
    )


if __name__ == "__main__":
    main()
